SELECT * FROM EMPLOYEE

--17. Display FIRSTNAME and LASTNAME in lowercase and uppercase. 
SELECT UPPER(FIRSTNAME),UPPER(LASTNAME) FROM EMPLOYEE
SELECT LOWER(FIRSTNAME),LOWER(LASTNAME) FROM EMPLOYEE

--18. Display full name by combining FIRSTNAME and LASTNAME. 
SELECT CONCAT(FIRSTNAME,LASTNAME) FROM EMPLOYEE

--19. Display FIRSTNAME with first 3 characters only. 
SELECT LEFT(FIRSTNAME,3) FROM EMPLOYEE

--20. Display LASTNAME with last 2 characters only. 
SELECT RIGHT(LASTNAME,2) FROM EMPLOYEE

--21. Display length of each employee’s FIRSTNAME. 
SELECT LEN(FIRSTNAME) FROM EMPLOYEE

--22. Display FIRSTNAME after replacing ‘A’ with ‘@’. 
SELECT REPLACE(FIRSTNAME,'A','@') FROM EMPLOYEE

--23. Display FIRSTNAME and LASTNAME with - between them using CONCAT.
SELECT CONCAT(FIRSTNAME,'-',LASTNAME) FROM EMPLOYEE
