--11. Display 5th highest SPI.
SELECT SNAME, SPI, D_R
FROM (
    SELECT SNAME, SPI,
           DENSE_RANK() OVER (ORDER BY SPI DESC) AS D_R
    FROM STUDENT
) AS Ranked
WHERE D_R = 5;


--12. Display 6th highest SPI.
SELECT SNAME, SPI, D_R
FROM (
    SELECT SNAME, SPI,
           DENSE_RANK() OVER (ORDER BY SPI DESC) AS D_R
    FROM STUDENT
) AS Ranked
WHERE D_R = 6;


--13. Display students having same ranking.
SELECT SNAME,SPI_WISE_RANK
FROM (SELECT *,
DENSE_RANK() OVER(ORDER BY SPI DESC) AS SPI_WISE_RANK
FROM STUDENT) X
WHERE SPI_WISE_RANK IN(
      SELECT RNK 
      FROM 
      (SELECT SNAME,SPI,DENSE_RANK() OVER(ORDER BY SPI DESC) AS RNK
      FROM STUDENT) DATA
      GROUP BY RNK
      HAVING COUNT(*) > 1)

--14. Display SNAME, Previous SPI, Current SPI and Next SPI based on ascending order of SPI.
SELECT SNAME,SPI,LAG(SPI) OVER(ORDER BY SPI DESC) AS LAG_SPI,
LEAD(SPI) OVER(ORDER BY SPI DESC) AS LEAD_SPI
FROM STUDENT

--15. Display topper of each branch.
SELECT SNAME, SPI, BRANCH
FROM (
    SELECT SNAME, SPI, BRANCH,
           DENSE_RANK() OVER (PARTITION BY BRANCH ORDER BY SPI DESC) AS D_R
    FROM STUDENT
) AS Ranked
WHERE D_R = 1;
