SELECT * FROM STADIUM
SELECT * FROM TEAM
SELECT * FROM PLAYER

--1. DISPLAY PLAYERS WHO BELONG TO TEAMS LOCATED IN ‘MUMBAI’. 
SELECT PLAYER_FIRST_NAME,PLAYER_LAST_NAME 
FROM PLAYER P
JOIN TEAM T
ON P.TEAM_ID = T.TEAM_ID
JOIN STADIUM S
ON S.Stadium_id = T.HOME_STADIUM_ID
WHERE S.Stadium_city = 'MUMBAI'

--2. DISPLAY ALL TEAMS AND PLAYERS. 
SELECT TEAM_NAME, PLAYER_FIRST_NAME,PLAYER_LAST_NAME 
FROM PLAYER P
FULL JOIN TEAM T
ON P.TEAM_ID = T.TEAM_ID

--3. DISPLAY PLAYERS ALONG WITH TEAM WINS AND STADIUM CITY.
SELECT PLAYER_FIRST_NAME,PLAYER_LAST_NAME,TEAM_WINS,STADIUM_CITY
FROM PLAYER P
JOIN TEAM T
ON P.TEAM_ID = T.TEAM_ID
JOIN STADIUM S
ON S.Stadium_id = T.HOME_STADIUM_ID

--4. DISPLAY TEAM NAME AND NUMBER OF PLAYERS IN EACH TEAM. 
SELECT TEAM_NAME,COUNT(P.PLAYER_ID)
FROM TEAM T
JOIN PLAYER P
ON P.TEAM_ID = T.TEAM_ID
GROUP BY TEAM_NAME

--5. DISPLAY TEAM NAME, COACH, AND NUMBER OF BOWLERS IN EACH TEAM. 
SELECT T.TEAM_NAME,T.TEAM_COACH,SUM(CASE WHEN P.PLAYER_ROLE = 'BOWLER' THEN 1 ELSE 0 END) AS BOLWERS
FROM TEAM T
JOIN PLAYER P
ON T.TEAM_ID = P.TEAM_ID
GROUP BY T.TEAM_NAME, T.TEAM_COACH;

--6. DISPLAY TEAM NAME WITH COUNT OF BATSMEN, BOWLERS, AND ALL-ROUNDERS. 
SELECT TEAM_NAME,
SUM(CASE WHEN PLAYER_ROLE = 'BATSMEN' THEN 1 ELSE 0 END) AS BATSMEN,
SUM(CASE WHEN PLAYER_ROLE = 'BOWLER' THEN 1 ELSE 0 END) AS BOWLER,
SUM(CASE WHEN PLAYER_ROLE = 'ALL-ROUNDER' THEN 1 ELSE 0 END) AS ALL_ROUNDER
FROM TEAM T
JOIN PLAYER P
ON T.TEAM_ID = P.PLAYER_ID

--7. DISPLAY STADIUMS WHERE TEAMS HAVE WON MORE THAN 10 MATCHES.
SELECT STADIUM_NAME
FROM STADIUM S
JOIN TEAM T
ON S.Stadium_id = T.HOME_STADIUM_ID
WHERE T.TEAM_WINS > 10

--8. DISPLAY TEAM NAME AND NUMBER OF PLAYERS WHOSE MATCHES PLAYED IS GREATER THAN 25. 
SELECT TEAM_NAME,SUM(CASE WHEN PLAYER_MATCHES_PLAYED > 25 THEN 1 ELSE 0 END)
FROM TEAM T
JOIN PLAYER P
ON T.TEAM_ID = P.TEAM_ID

--9. DISPLAY TEAM NAME AND TOTAL NUMBER OF PLAYERS HAVING JERSEY NUMBER GREATER THAN 30. 
SELECT TEAM_NAME,SUM(CASE WHEN PLAYER_JERSEY_NUMBER > 30 THEN 1 ELSE 0 END)
FROM TEAM T
JOIN PLAYER P
ON T.TEAM_ID = P.TEAM_ID

--10. DISPLAY TEAM NAME AND TOTAL MATCHES PLAYED BY ITS PLAYERs.
SELECT TEAM_NAME,SUM(PLAYER_MATCHES_PLAYED)
FROM TEAM T
JOIN PLAYER P
ON T.TEAM_ID = P.TEAM_ID
GROUP BY TEAM_NAME
