SELECT * FROM STADIUM
SELECT * FROM TEAM
SELECT * FROM PLAYER

--16. DISPLAY TEAMS HAVING MORE ALL-ROUNDERS THAN BOWLERS. 
SELECT TEAM_NAME
FROM TEAM T
JOIN PLAYER P
ON T.TEAM_ID = P.TEAM_ID
GROUP BY TEAM_NAME
HAVING SUM(CASE WHEN PLAYER_ROLE = 'ALL-ROUNDER' THEN 1 ELSE 0 END)
	   > SUM(CASE WHEN PLAYER_ROLE = 'BOWLER' THEN 1 ELSE 0 END)

--17. DISPLAY TEAMS WHERE DIFFERENCE BETWEEN MAX AND MIN PLAYER MATCHES IS GREATER THAN 5. 
SELECT TEAM_NAME 
FROM TEAM T
JOIN PLAYER P
ON T.TEAM_ID = P.TEAM_ID
GROUP BY TEAM_NAME
HAVING MAX(PLAYER_MATCHES_PLAYED) - MIN(PLAYER_MATCHES_PLAYED) > 5

--18. DISPLAY STADIUM CITY AND TOTAL WINS OF TEAMS IN THAT CITY. 
SELECT STADIUM_CITY,SUM(TEAM_WINS)
FROM STADIUM S
JOIN TEAM T
ON S.Stadium_id = T.HOME_STADIUM_ID
GROUP BY Stadium_city

--19. DISPLAY TEAM NAME AND TOTAL NUMBER OF PLAYERS FOR EACH ROLE (GROUPED BY ROLE). 
SELECT TEAM_NAME,PLAYER_ROLE,COUNT(PLAYER_ID)
FROM TEAM T
JOIN PLAYER P
ON T.TEAM_ID = P.TEAM_ID
GROUP BY TEAM_NAME,PLAYER_ROLE

--20. DISPLAY TEAM NAME AND TOTAL NUMBER OF PLAYERS WHOSE NAME STARTS WITH ‘A’ 
SELECT TEAM_NAME,SUM(CASE WHEN PLAYER_FIRST_NAME LIKE 'A%' THEN 1 ELSE 0 END)
FROM TEAM T
JOIN PLAYER P
ON T.TEAM_ID = P.TEAM_ID
GROUP BY TEAM_NAME