--1. DISPLAY ALL UNIQUE CUSTOMER NAMES FROM ONLINE_CUSTOMER AND OFFLINE_CUSTOMER. 
SELECT NAME FROM ONLINE_CUSTOMER
UNION
SELECT NAME FROM OFFLINE_CUSTOMER;

--2. DISPLAY ALL UNIQUE CUSTOMER CITIES FROM ONLINE_CUSTOMER AND OFFLINE_CUSTOMER.
SELECT CITY FROM ONLINE_CUSTOMER
UNION
SELECT CITY FROM OFFLINE_CUSTOMER;

--3. DISPLAY DUPLICATE CUSTOMER NAMES FROM BOTH TABLES ONLINE_CUSTOMER AND OFFLINE_CUSTOMER. 
SELECT NAME FROM ONLINE_CUSTOMER
INTERSECT
SELECT NAME FROM OFFLINE_CUSTOMER;

--4. DISPLAY UNIQUE CUSTOMER IDS FROM BOTH TABLES.
SELECT CID FROM ONLINE_CUSTOMER
UNION
SELECT CID FROM OFFLINE_CUSTOMER;

--5. DISPLAY ALL GOLD MEMBERSHIP CUSTOMER NAMES AND ONLINE CUSTOMER NAMES USING UNION.
SELECT NAME FROM CUSTOMER WHERE MEMBERSHIP = 'GOLD'
UNION
SELECT NAME FROM ONLINE_CUSTOMER;

--6. DISPLAY ALL CUSTOMER NAMES FROM CUSTOMER AND ONLINE_CUSTOMER USING UNION. 
SELECT NAME FROM CUSTOMER
UNION
SELECT NAME FROM ONLINE_CUSTOMER;

--7. DISPLAY ALL CITIES FROM CUSTOMER AND OFFLINE_CUSTOMER USING UNION. 
SELECT CITY FROM CUSTOMER
UNION
SELECT CITY FROM OFFLINE_CUSTOMER;

--8.DISPLAY ALL CUSTOMER IDS FROM CUSTOMER AND OFFLINE_CUSTOMER USING UNION ALL. 
SELECT CID FROM CUSTOMER
UNION ALL
SELECT CID FROM OFFLINE_CUSTOMER;

--9.DISPLAY ALL CUSTOMER NAMES FROM RAJKOT CITY USING UNION.
SELECT NAME FROM CUSTOMER WHERE CITY = 'RAJKOT'
UNION
SELECT NAME FROM ONLINE_CUSTOMER WHERE CITY = 'RAJKOT'
UNION
SELECT NAME FROM OFFLINE_CUSTOMER WHERE CITY = 'RAJKOT';

--10.DISPLAY ALL CUSTOMER NAMES STARTING WITH R FROM BOTH TABLES USING UNION. 
SELECT NAME FROM CUSTOMER WHERE NAME LIKE 'R%'
UNION
SELECT NAME FROM ONLINE_CUSTOMER WHERE NAME LIKE 'R%'
UNION
SELECT NAME FROM OFFLINE_CUSTOMER WHERE NAME LIKE 'R%';

--11. DISPLAY CUSTOMERS WHO ARE BOTH ONLINE AND OFFLINE.
SELECT NAME FROM ONLINE_CUSTOMER
INTERSECT
SELECT NAME FROM OFFLINE_CUSTOMER;

--12.  DISPLAY CUSTOMER IDS EXISTING IN BOTH ONLINE_CUSTOMER AND OFFLINE_CUSTOMER.
SELECT CID FROM ONLINE_CUSTOMER
INTERSECT
SELECT CID FROM OFFLINE_CUSTOMER;

--13.  DISPLAY CUSTOMER NAMES EXISTING ONLY IN ONLINE_CUSTOMER. 
SELECT NAME FROM ONLINE_CUSTOMER
EXCEPT
SELECT NAME FROM OFFLINE_CUSTOMER;

--14. DISPLAY CUSTOMER NAMES EXISTING ONLY IN OFFLINE_CUSTOMER.
SELECT NAME FROM OFFLINE_CUSTOMER
EXCEPT
SELECT NAME FROM ONLINE_CUSTOMER;

--15. DISPLAY CITIES AVAILABLE IN BOTH ONLINE_CUSTOMER AND OFFLINE_CUSTOMER. 
SELECT CITY FROM ONLINE_CUSTOMER
INTERSECT
SELECT CITY FROM OFFLINE_CUSTOMER;