--26.  CUSTOMERS PRESENT IN AT LEAST TWO TABLES.
SELECT NAME FROM CUSTOMER
INTERSECT
SELECT NAME FROM ONLINE_CUSTOMER
UNION
SELECT NAME FROM CUSTOMER
INTERSECT
SELECT NAME FROM OFFLINE_CUSTOMER
UNION
SELECT NAME FROM ONLINE_CUSTOMER
INTERSECT
SELECT NAME FROM OFFLINE_CUSTOMER;

--27.  DISPLAY ALL CUSTOMER NAMES FROM CUSTOMER TABLE EXCLUDING CUSTOMERS AVAILABLE IN BOTH ONLINE_CUSTOMER AND OFFLINE_CUSTOMER. 
SELECT NAME FROM CUSTOMER
EXCEPT
(SELECT NAME FROM ONLINE_CUSTOMER
INTERSECT
SELECT NAME FROM OFFLINE_CUSTOMER);

--28.DISPLAY CUSTOMER NAMES WHO ARE PRESENT IN BOTH ONLINE_CUSTOMER AND OFFLINE_CUSTOMER BUT NOT PLATINIUM MEMBERS. 
SELECT NAME FROM ONLINE_CUSTOMER
INTERSECT
SELECT NAME FROM OFFLINE_CUSTOMER
EXCEPT
SELECT NAME FROM CUSTOMER WHERE MEMBERSHIP = 'PLATINUM';

--29.  DISPLAY CUSTOMER NAMES WHO ARE EITHER ONLINE OR OFFLINE BUT NOT BOTH.
SELECT NAME FROM ONLINE_CUSTOMER
EXCEPT
SELECT NAME FROM OFFLINE_CUSTOMER
UNION
SELECT NAME FROM OFFLINE_CUSTOMER
EXCEPT
SELECT NAME FROM ONLINE_CUSTOMER;

--30.  DISPLAY CUSTOMER IDS PRESENT IN CUSTOMER TABLE BUT MISSING FROM BOTH ONLINE_CUSTOMER AND OFFLINE_CUSTOMER.
SELECT CID FROM CUSTOMER
EXCEPT
(SELECT CID FROM ONLINE_CUSTOMER
UNION
SELECT CID FROM OFFLINE_CUSTOMER);