--16.DISPLAY CUSTOMER NAMES WHO ARE GOLD MEMBERS AND ONLINE CUSTOMERS. 
SELECT NAME FROM CUSTOMER WHERE MEMBERSHIP = 'GOLD'
INTERSECT
SELECT NAME FROM ONLINE_CUSTOMER;

--17. DISPLAY CUSTOMER NAMES WHO ARE PLATINUM MEMBERS BUT NOT ONLINE CUSTOMERS.
SELECT NAME FROM CUSTOMER WHERE MEMBERSHIP = 'PLATINUM'
EXCEPT
SELECT NAME FROM ONLINE_CUSTOMER;

--18. DISPLAY CUSTOMER IDS WHO ARE ONLINE CUSTOMERS BUT NOT OFFLINE CUSTOMERS. 
SELECT CID FROM ONLINE_CUSTOMER
EXCEPT
SELECT CID FROM OFFLINE_CUSTOMER;

--19.DISPLAY CUSTOMER IDS WHO ARE OFFLINE CUSTOMERS BUT NOT ONLINE CUSTOMERS. 
SELECT CID FROM OFFLINE_CUSTOMER
EXCEPT
SELECT CID FROM ONLINE_CUSTOMER;

--20. DISPLAY CUSTOMERS WHO ARE PRESENT IN CUSTOMER TABLE BUT NOT IN ONLINE_CUSTOMER. 
SELECT NAME FROM CUSTOMER
EXCEPT
SELECT NAME FROM ONLINE_CUSTOMER;

--21 DISPLAY CUSTOMERS WHO ARE BOTH GOLD MEMBERS AND AVAILABLE IN OFFLINE_CUSTOMER.
SELECT NAME FROM CUSTOMER WHERE MEMBERSHIP = 'GOLD'
INTERSECT
SELECT NAME FROM OFFLINE_CUSTOMER;

--22.DISPLAY ALL DISTINCT CITIES FROM ALL THREE TABLES. 
SELECT CITY FROM CUSTOMER
UNION
SELECT CITY FROM ONLINE_CUSTOMER
UNION
SELECT CITY FROM OFFLINE_CUSTOMER;

--23. DISPLAY CUSTOMERS WHO ARE ONLINE CUSTOMERS AND BELONG TO SURAT CITY USING INTERSECT.
SELECT NAME FROM ONLINE_CUSTOMER WHERE CITY = 'SURAT'
INTERSECT
SELECT NAME FROM CUSTOMER WHERE CITY = 'SURAT';

--24. DISPLAY CUSTOMERS WHO ARE OFFLINE CUSTOMERS BUT NOT FROM RAJKOT CITY USING MINUS. 
SELECT NAME FROM OFFLINE_CUSTOMER
EXCEPT
SELECT NAME FROM OFFLINE_CUSTOMER WHERE CITY = 'RAJKOT';

--25. DISPLAY CUSTOMERS WHO ARE GOLD MEMBERS, ONLINE CUSTOMERS, AND FROM SURAT CITY USING INTERSECT.
SELECT NAME FROM CUSTOMER WHERE MEMBERSHIP = 'GOLD' AND CITY = 'SURAT'
INTERSECT
SELECT NAME FROM ONLINE_CUSTOMER WHERE CITY = 'SURAT';