CREATE TABLE EMPLOYEE_MASTER(
	EMPLOYEEID VARCHAR(50),
	NAME VARCHAR(50),
	MANAGERNO VARCHAR(50)
);
INSERT INTO EMPLOYEE_MASTER VALUES
('E01','TARUN',NULL),
('E02','ROHAN','E02'),
('E03','PRIYA','E01'),
('E04','MIALN','E03'),
('E05','JAY','E01'),
('E06','ANJANA','E04')

SELECT * FROM EMPLOYEE_MASTER

--16. RETRIEVE THE NAMES OF EMPLOYEE ALONG WITH THEIR MANAGER’S NAME FROM THE EMPLOYEE TABLE.
SELECT E1.NAME,E2.NAME
FROM EMPLOYEE_MASTER E1
JOIN EMPLOYEE_MASTER E2
ON E1.MANAGERNO = E2.EMPLOYEEID

--17. DISPLAY EMPLOYEES WHO ARE MANAGERS. 
SELECT NAME FROM EMPLOYEE_MASTER
WHERE MANAGERNO IS NOT NULL

--18. DISPLAY NUMBER OF EMPLOYEES WORKING UNDER EACH MANAGER. 
SELECT E1.NAME,COUNT(E2.EMPLOYEEID)
FROM EMPLOYEE_MASTER E1
JOIN EMPLOYEE_MASTER E2
ON E1.MANAGERNO = E2.EMPLOYEEID
GROUP BY E2.MANAGERNO

--19. DISPLAY THE EMPLOYEE’S NAME ALONG WITH THEIR MANAGER’S NAME AND SENIOR MANAGER NAME.
SELECT E1.NAME AS EMP,E2.NAME AS MANAGER,E3.NAME AS SENIOUR_MANAGER
FROM EMPLOYEE_MASTER E1
JOIN EMPLOYEE_MASTER E2
ON E1.MANAGERNO = E2.EMPLOYEEID
JOIN EMPLOYEE_MASTER E3
ON E2.MANAGERNO = E3.EMPLOYEEID

--20. DISPLAY MANAGERS AND COUNT OF EMPLOYEES UNDER THEM IN DESCENDING ORDER.  
SELECT E1.NAME,COUNT(E2.EMPLOYEEID)
FROM EMPLOYEE_MASTER E1
JOIN EMPLOYEE_MASTER E2
ON E1.MANAGERNO = E2.EMPLOYEEID
GROUP BY E1.MANAGERNO