SELECT * FROM PUBLISTER
SELECT * FROM AUTHOR
SELECT * FROM BOOK

--1. LIST ALL BOOKS WITH THEIR AUTHORS. 
SELECT TITLE,AUTHORNAME
FROM BOOK B
JOIN AUTHOR A 
ON B.AUTHORID = A.AUTHORID

--2. LIST ALL BOOKS WITH THEIR PUBLISHERS. 
SELECT TITLE,PUBLISTERNAME
FROM BOOK B
JOIN PUBLISTER P
ON B.PUBLISHERID = P.PUBLISTERID

--3. LIST ALL BOOKS WITH THEIR AUTHORS AND PUBLISHERS. 
SELECT TITLE,AUTHORNAME,PUBLISTERNAME
FROM BOOK B
JOIN AUTHOR A
ON B.AUTHORID = A.AUTHORID
JOIN PUBLISTER P
ON P.PUBLISTERID = B.PUBLISHERID

--4. LIST ALL BOOKS PUBLISHED AFTER 2010 WITH THEIR AUTHORS AND PUBLISHER AND PRICE. 
SELECT TITLE,AUTHORNAME,PUBLISTERNAME,PUBLICATIONYEAR,PRICE
FROM BOOK B
JOIN AUTHOR A
ON B.AUTHORID = A.AUTHORID
JOIN PUBLISTER P
ON P.PUBLISTERID = B.AUTHORID
WHERE B.PUBLICATIONYEAR > 2010

--5. LIST ALL AUTHORS AND THE NUMBER OF BOOKS THEY HAVE WRITTEN.
SELECT AUTHORNAME,COUNT(BOOKID)
FROM AUTHOR A
JOIN BOOK B
ON A.AUTHORID = B.AUTHORID
GROUP BY AUTHORNAME

--6. LIST ALL PUBLISHERS AND THE TOTAL PRICE OF BOOKS THEY HAVE PUBLISHED. 
SELECT PUBLISTERNAME,SUM(PRICE)
FROM PUBLISTER P
JOIN BOOK B
ON P.PUBLISTERID = B.PUBLISHERID
GROUP BY PUBLISTERNAME

--7. LIST AUTHORS WHO HAVE NOT WRITTEN ANY BOOKS.
SELECT AUTHORNAME 
FROM AUTHOR A
JOIN BOOK B
ON A.AUTHORID = B.AUTHORID
GROUP BY A.AUTHORNAME
HAVING COUNT(B.BOOKID) = 0

--8. DISPLAY THE TOTAL NUMBER OF BOOKS WRITTEN BY EACH AUTHOR ALONG WITH THE AVERAGE PRICE OF THEIR BOOKS. 
SELECT AUTHORNAME,COUNT(B.BOOKID),AVG(B.PRICE)
FROM AUTHOR A
JOIN BOOK B
ON A.AUTHORID = B.AUTHORID
GROUP BY AUTHORNAME

--9. LISTS EACH PUBLISHER ALONG WITH THE TOTAL NUMBER OF BOOKS THEY HAVE PUBLISHED, SORTED FROM HIGHEST TO LOWEST. 
SELECT PUBLISTERNAME,COUNT(BOOKID)
FROM PUBLISTER P
JOIN BOOK B
ON P.PUBLISTERID = B.PUBLISHERID
GROUP BY PUBLISTERNAME
ORDER BY COUNT(BOOKID) DESC

--10. DISPLAY NUMBER OF BOOKS PUBLISHED EACH YEAR.
SELECT PUBLICATIONYEAR,COUNT(BOOKID)
FROM PUBLISTER P
JOIN BOOK B
ON P.PUBLISTERID = B.PUBLISHERID
GROUP BY PUBLICATIONYEAR