SELECT * FROM PUBLISTER
SELECT * FROM AUTHOR
SELECT * FROM BOOK

--11. LIST THE PUBLISHERS WHOSE TOTAL BOOK PRICES EXCEED 500, ORDERED BY THE TOTAL PRICE.
SELECT PUBLISTERNAME,SUM(PRICE)
FROM PUBLISTER P
JOIN BOOK B
ON P.PUBLISTERID = B.PUBLISHERID
GROUP BY PUBLISTERNAME
HAVING SUM(PRICE) >= 500
ORDER BY SUM(PRICE)

--12. LIST MOST EXPENSIVE BOOK FOR EACH AUTHOR, SORT IT WITH THE HIGHEST PRICE. 
SELECT AUTHORNAME,TITLE,PRICE
FROM AUTHOR A
JOIN BOOK B
ON A.AUTHORID = B.AUTHORID
GROUP BY AUTHORNAME

--13. DISPLAY PUBLISHER NAME AND DIFFERENCE BETWEEN MAXIMUM AND MINIMUM BOOK PRICE. 
SELECT PUBLISTERNAME,MAX(PRICE) - MIN(PRICE)
FROM PUBLISTER P
JOIN BOOK B
ON P.PUBLISTERID = B.PUBLISHERID
GROUP BY PUBLISTERNAME

--14. LIST PUBLISHER NAME AND TOTAL PRICE OF BOOKS PUBLISHED EACH YEAR. 
SELECT PUBLISTERNAME,SUM(PRICE),PUBLICATIONYEAR
FROM PUBLISTER P
JOIN BOOK B
ON P.PUBLISTERID = B.PUBLISHERID
GROUP BY PUBLICATIONYEAR

--15. DISPLAY AUTHOR NAME AND TOTAL PRICE OF BOOKS SORTED BY HIGHEST TOTAL PRICE. 
SELECT AUTHORNAME,SUM(PRICE)
FROM AUTHOR A
JOIN BOOK B
ON A.AUTHORID = B.AUTHORID
GROUP BY AUTHORNAME
ORDER BY SUM(PRICE) DESC
