CREATE TABLE CUSTOMERS ( 
CUSTOMERID INT PRIMARY KEY, 
CUSTOMERNAME VARCHAR (100) NOT NULL, 
CITY VARCHAR (100), 
MEMBERSHIP VARCHAR (20) 
);

INSERT INTO CUSTOMERS (CUSTOMERID, CUSTOMERNAME, CITY, MEMBERSHIP) VALUES 
(101, 'ALICE', 'MUMBAI', 'GOLD'), 
(102, 'BOB', 'DELHI', 'SILVER'), 
(103, 'CHARLIE', 'PUNE', 'GOLD'), 
(104, 'DAVID', 'AHMEDABAD', 'SILVER'), 
(105, 'EVA', 'MUMBAI', 'PLATINUM');

CREATE TABLE ORDERS ( 
ORDERID INT PRIMARY KEY, 
CUSTOMERID INT NOT NULL, 
PRODUCT VARCHAR (100) NOT NULL, 
CATEGORY VARCHAR (50), 
QUANTITY INT NOT NULL, 
PRICE DECIMAL (10,2) NOT NULL, 
FOREIGN KEY (CUSTOMERID) REFERENCES CUSTOMERS (CUSTOMERID) 
); 

INSERT INTO ORDERS (ORDERID, CUSTOMERID, PRODUCT, CATEGORY, QUANTITY, PRICE) VALUES 
(201, 101, 'LAPTOP', 'ELECTRONICS', 1, 70000), 
(202, 101, 'MOUSE', 'ELECTRONICS', 2, 800), 
(203, 102, 'CHAIR', 'FURNITURE', 3, 2500), 
(204, 103, 'PHONE', 'ELECTRONICS', 1, 45000), 
(205, 104, 'TABLE', 'FURNITURE', 2, 6000), 
(206, 105, 'LAPTOP', 'ELECTRONICS', 2, 70000), 
(207, 105, 'PRINTER', 'ELECTRONICS', 1, 12000), 
(208, 103, 'DESK', 'FURNITURE', 1, 8000); 

SELECT * FROM CUSTOMERS
SELECT * FROM ORDERS

--) CREATE A VIEW NAMED CUSTOMERORDERS DISPLAYING: 
--• CUSTOMER NAME 
--• CITY 
--• PRODUCT 
--• CATEGORY 
--• QUANTITY 
--• PRICE 

CREATE VIEW CUSTOMERORDERS
AS
SELECT CUSTOMERNAME,CITY,PRODUCT,CATEGORY,QUANTITY,PRICE
FROM CUSTOMERS C
JOIN ORDERS O
ON C.CUSTOMERID = O.CUSTOMERID

SELECT * FROM CUSTOMERORDERS

--2) CREATE A VIEW NAMED GOLDCUSTOMERSORDERS THAT DISPLAYS ALL ORDERS PLACED BY GOLD MEMBERS. 
CREATE VIEW GOLDCUTOMERSORDERS
AS
SELECT * 
FROM CUSTOMERS C
RIGHT JOIN ORDERS O
ON C.CUSTOMERID = O.CUSTOMERID
WHERE MEMBERSHIP = 'GOLD'

--3) CREATE A VIEW ELECTRONICORDERS DISPLAYING ONLY ELECTRONICS ORDERS. 
CREATE VIEW ELECTRONICORDERS
AS
SELECT *
FROM ORDERS O
JOIN CUSTOMERS C
ON C.CUSTOMERID = O.CUSTOMERID
WHERE CATEGORY = 'ELECTRONICS'

--4) CREATE A VIEW CUSTOMERPURCHASESUMMARY SHOWING THE TOTAL PURCHASE AMOUNT FOR EACH CUSTOMER. 
--(PURCHASE AMOUNT = QUANTITY * PRICE) 
CREATE VIEW CUSTOMERPURCHASESUMMARY
AS
SELECT CUSTOMERNAME,SUM(QUANTITY*PRICE)
FROM CUSTOMERS C
JOIN ORDERS O
ON C.CUSTOMERID = O.CUSTOMERID
GROUP BY CUSTOMERNAME

--5) CREATE A VIEW CUSTOMERORDERCOUNT SHOWING: 
--• CUSTOMER NAME 
--• NUMBER OF ORDERS PLACED 
CREATE VIEW CUSTOMERORDERCOUNT
AS
SELECT CUSTOMERNAME,COUNT(ORDERID) AS ORDERS_PLACED
FROM CUSTOMERS C
JOIN ORDERS O
ON C.CUSTOMERID = O.CUSTOMERID
GROUP BY CUSTOMERNAME

--6) CREATE A VIEW CATEGORYSALES DISPLAYING: 
--• CATEGORY 
--• NUMBER OF ORDERS 
--• TOTAL QUANTITY SOLD
CREATE VIEW CATEGORYSALES
AS
SELECT CATEGORY,COUNT(ORDERID),COUNT(QUANTITY)
FROM CUSTOMERS C
JOIN ORDERS O
ON C.CUSTOMERID = O.CUSTOMERID
GROUP BY CATEGORY

--7) CREATE A VIEW AMOUNTDETAILS DISPLAYING: 
--• MEMBERSHIP TYPE 
--• AVERAGE PURCHASE AMOUNT PER ORDER  
CREATE VIEW AMOUNTDETAILS
AS
SELECT MEMBERSHIP,AVG(PRICE*QUANTITY)
FROM CUSTOMERS C
JOIN ORDERS O
ON C.CUSTOMERID = O.CUSTOMERID
GROUP BY MEMBERSHIP

--8) CREATE A VIEW CITYSALES DISPLAYING: 
--• CITY 
--• TOTAL CUSTOMERS WHO PLACED ORDERS 
--• TOTAL PURCHASE AMOUNT
CREATE VIEW CITYSALES
AS
SELECT CITY,COUNT(CUSTOMERID),SUM(QUANTITY*PRICE)
FROM CUSTOMERS C
JOIN ORDERS O
ON C.CUSTOMERID = O.CUSTOMERID
GROUP BY CITY

--9) CREATE A VIEW CUSTOMERSALES DISPLAYING: 
--• CUSTOMER NAME 
--• MEMBERSHIP 
--• TOTAL QUANTITY PURCHASED 
--• TOTAL AMOUNT SPENT 
CREATE VIEW CUSTOMERSALES
AS
SELECT CUSTOMERNAME,MEMBERSHIP,COUNT(QUANTITY),SUM(QUANTITY*PRICE)
FROM CUSTOMERS C
JOIN ORDERS O
ON C.CUSTOMERID = O.CUSTOMERID
GROUP BY CUSTOMERNAME,MEMBERSHIP

--10) CREATE A VIEW CUSTOMERMEMBERSHIP DISPLAYING: 
--• CATEGORY 
--• MEMBERSHIP TYPE 
--• TOTAL SALES 
--• AVERAGE QUANTITY PURCHASEd 
CREATE VIEW CUSTOMERMEMBERSHIP
AS
SELECT CATEGORY,MEMBERSHIP,SUM(QUANTITY*PRICE),AVG(QUANTITY)
FROM CUSTOMERS C
JOIN ORDERS O
ON C.CUSTOMERID = O.CUSTOMERID
GROUP BY CATEGORY,MEMBERSHIP