SELECT * FROM EMPLOYEE

--1. CREATE A VIEW EMPLOYEE_ALL WITH ALL COLUMNS. 
CREATE VIEW EMPLOYEE_ALL
AS 
SELECT * FROM EMPLOYEE

SELECT * FROM EMPLOYEE_ALL

--2. CREATE A VIEW EMPLOYEE_NAMEDEPTSALARY HAVING COLUMNS FIRSTNAME, DEPARTMENT AND SALARY. 
CREATE VIEW EMPLOYEE_NAMEDEPTSALARY
AS
SELECT FIRSTNAME,DEPARTMENT,SALARY
FROM EMPLOYEE

SELECT * FROM EMPLOYEE_NAMEDEPTSALARY

--3. CREATE A VIEW EMPLOYEE_BASIC HAVING COLUMNS EID, FIRSTNAME AND CITY. 
CREATE VIEW EMPLOYEE_BASIC
AS
SELECT EID,FIRSTNAME,CITY
FROM EMPLOYEE

SELECT * FROM EMPLOYEE_BASIC

--4. CREATE A VIEW IT_EMPLOYEES THAT DISPLAYS IT DEPARTMENT DATA ONLY. 
CREATE VIEW IT_EMPLOYEES
AS
SELECT EID,DEPARTMENT
FROM EMPLOYEE

SELECT * FROM IT_EMPLOYEES

--5. CREATE A VIEW HR_EMPLOYEES THAT DISPLAYS HR DEPARTMENT DATA ONLY. 
CREATE VIEW HR_EMPLOYEES
AS
SELECT * FROM EMPLOYEE
WHERE DEPARTMENT = 'HR'

SELECT * FROM HR_EMPLOYEES

--6. CREATE A VIEW EMPLOYEE_2026 THAT DISPLAYS EMPLOYEES JOINED IN 2026 ONLY. 
CREATE VIEW EMPLOYEE_2026
AS
SELECT * FROM EMPLOYEE
WHERE JOININGYEAR = 2026

SELECT * FROM EMPLOYEE_2026

--7. CREATE A VIEW PATEL_EMPLOYEES THAT DISPLAYS EMPLOYEES WHOSE LAST NAME IS PATEL. 
CREATE VIEW PATEL_EMPLOYEES
AS
SELECT * FROM EMPLOYEE
WHERE LASTNAME = 'PATEL'

SELECT * FROM PATEL_EMPLOYEES


--8. CREATE A VIEW HIGH_SALARY_EMP HAVING ALL COLUMNS BUT EMPLOYEES WHOSE SALARY IS MORE THAN 12000. 
CREATE VIEW HIGH_SALARY_EMP
AS
SELECT * FROM EMPLOYEE
WHERE SALARY > 12000

SELECT * FROM HIGH_SALARY_EMP

--9. CREATE A VIEW THAT DISPLAYS INFORMATION OF ALL EMPLOYEES WHOSE SALARY IS ABOVE 14000. 
CREATE VIEW HIGH_SAL
AS
SELECT * FROM EMPLOYEE
WHERE SALARY > 14000

SELECT * FROM HIGH_SAL

--10. CREATE A VIEW THAT DISPLAYS EMPLOYEES HAVING SALARY BELOW 10000. 
CREATE VIEW SAL
AS
SELECT * FROM EMPLOYEE
WHERE SALARY < 10000

SELECT * FROM SAL

--11. CREATE A VIEW SERVER_DEPT THAT DISPLAYS SERVER DEPARTMENT EMPLOYEES ONLY. 
CREATE VIEW SERVER_DEPT
AS
SELECT * FROM EMPLOYEE
WHERE DEPARTMENT = 'SERVER'

SELECT * FROM SERVER_DEPT

--12. INSERT A NEW RECORD INTO EMPLOYEE_BASIC VIEW. (111, MEET, SURAT) 
INSERT INTO EMPLOYEE_BASIC VALUES
(111,'MEET','SURAT')

SELECT * FROM EMPLOYEE_BASIC
--13. UPDATE THE DEPARTMENT OF DEEP FROM ADMIN TO IT IN EMPLOYEE_NAMEDEPTSALARY VIEW.
UPDATE EMPLOYEE_NAMEDEPTSALARY SET DEPARTMENT = 'IT'
FROM EMPLOYEE_NAMEDEPTSALARY
WHERE FIRSTNAME = 'DEEP' AND DEPARTMENT = 'ADMIN'

SELECT * FROM EMPLOYEE_NAMEDEPTSALARY
--14. DELETE AN EMPLOYEE WHOSE EID IS 107 FROM EMPLOYEE_BASIC VIEW.
DELETE FROM EMPLOYEE_BASIC
WHERE EID = 107

SELECT * FROM EMPLOYEE_BASIC
--15. DROP IT_EMPLOYEES VIEW FROM THE DATABASE.
DROP VIEW IT_EMPLOYEES