--16. CREATE A VIEW ADMIN_EMPLOYEES THAT DISPLAYS ADMIN DEPARTMENT EMPLOYEES ONLY. 
CREATE VIEW ADMIN_EMPLOYEES
AS
SELECT * FROM EMPLOYEE
WHERE DEPARTMENT = 'ADMIN'

SELECT * FROM ADMIN_EMPLOYEES

--17. CREATE A VIEW FEMALE_EMPLOYEES THAT DISPLAYS FEMALE EMPLOYEE DATA ONLY. 
CREATE VIEW FEMALE_EMPLOYEES
AS
SELECT * FROM EMPLOYEE
WHERE GENDER = 'FEMALE'

SELECT * FROM FEMALE_EMPLOYEES

--18. CREATE A VIEW MALE_EMPLOYEES THAT DISPLAYS MALE EMPLOYEE DATA ONLY. 
CREATE VIEW MALE_EMPLOYEES
AS
SELECT * FROM EMPLOYEE
WHERE GENDER = 'MALE'

SELECT * FROM MALE_EMPLOYEES

--19. CREATE A VIEW RAJKOT_EMPLOYEES THAT DISPLAYS EMPLOYEES FROM RAJKOT CITY ONLY. 
CREATE VIEW RAJKOT_EMPLOYEES
AS
SELECT * FROM EMPLOYEE
WHERE CITY = 'RAJKOT'

SELECT * FROM RAJKOT_EMPLOYEES

--20. CREATE A VIEW AHMEDABAD_EMPLOYEES THAT DISPLAYS EMPLOYEES FROM AHMEDABAD CITY ONLY. 
CREATE VIEW AHMEDABAD_EMPLOYEES
AS
SELECT * FROM EMPLOYEE
WHERE CITY = 'AHMEDABAD'

SELECT * FROM AHMEDABAD_EMPLOYEES

--21. CREATE A VIEW SALARY_BETWEEN THAT DISPLAYS EMPLOYEES WHOSE SALARY IS BETWEEN 10000 AND 14000. 
CREATE VIEW SALARY_BETWEEN
AS
SELECT * FROM EMPLOYEE
WHERE SALARY BETWEEN 10000 AND 14000

SELECT * FROM SALARY_BETWEEN

--22. CREATE A VIEW RECENT_EMPLOYEES THAT DISPLAYS EMPLOYEES JOINED AFTER 2023. 
CREATE VIEW RECENT_EMPLOYEES 
AS
SELECT * FROM EMPLOYEE
WHERE JOININGYEAR > 2023

SELECT * FROM RECENT_EMPLOYEES

--23. CREATE A VIEW OLD_EMPLOYEES THAT DISPLAYS EMPLOYEES JOINED BEFORE 2023. 
CREATE VIEW OLD_EMPLOYEES
AS
SELECT * FROM EMPLOYEE
WHERE JOININGYEAR < 2023

SELECT * FROM OLD_EMPLOYEES

--24. CREATE A VIEW EMPLOYEES_START_R THAT DISPLAYS EMPLOYEES WHOSE FIRST NAME STARTS WITH R. 
CREATE VIEW EMPLOYEE_START_R 
AS
SELECT * FROM EMPLOYEE
WHERE FIRSTNAME LIKE 'R%'

SELECT * FROM EMPLOYEE_START_R

--25. CREATE A VIEW EMPLOYEES_END_A THAT DISPLAYS EMPLOYEES WHOSE FIRST NAME ENDS WITH A. 
CREATE VIEW EMPLOYEES_END_A
AS
SELECT * FROM EMPLOYEE
WHERE FIRSTNAME LIKE '%A'

SELECT * FROM EMPLOYEES_END_A
