--26. CREATE A VIEW EMPLOYEES_NAMECONTAINS_H THAT DISPLAYS EMPLOYEES WHOSE FIRST NAME CONTAINS H. 
CREATE VIEW EMPLOYEES_NAMECONTAINS_H
AS
SELECT * FROM EMPLOYEE
WHERE FIRSTNAME LIKE '%H%'

SELECT * FROM EMPLOYEES_NAMECONTAINS_H

--27. CREATE A VIEW FOR THE EMPLOYEES WHOSE FIRST NAME CONTAINS VOWELS. 
CREATE VIEW VOWELS
AS
SELECT * FROM EMPLOYEE
WHERE FIRSTNAME LIKE '%[AEIOU]%'

SELECT * FROM VOWELS

--28. CREATE A VIEW FOURLETTER_NAME HAVING EID, FIRSTNAME AND DEPARTMENT COLUMNS IN WHICH FIRSTNAME CONSISTS OF FOUR LETTERS. 
CREATE VIEW FOURLETTER_NAME
AS
SELECT EID,FIRSTNAME,DEPARTMENT FROM EMPLOYEE
WHERE LEN(FIRSTNAME) = 4

SELECT * FROM FOURLETTER_NAME

--29. CREATE A VIEW FOR THE EMPLOYEES WHOSE NAME STARTS WITH M AND ENDS WITH N. 
CREATE VIEW M_N__EMPLOYEES
AS
SELECT * FROM EMPLOYEE
WHERE FIRSTNAME LIKE 'M%N'


SELECT * FROM M_N__EMPLOYEES

--30. CREATE A VIEW TRANSPORT_DEPT THAT DISPLAYS TRANSPORT DEPARTMENT EMPLOYEES ONLY. 
CREATE VIEW TRANSPORT_DEPT
AS
SELECT * FROM EMPLOYEE
WHERE DEPARTMENT = 'TRANSPORT'

SELECT * FROM TRANSPORT_DEPT
