SELECT * FROM DEPARTMENT
SELECT * FROM PERSON

--1. COMBINE INFORMATION FROM PERSON AND DEPARTMENT TABLE USING CROSS JOIN OR CARTESIAN PRODUCT. 
SELECT * 
FROM PERSON
CROSS JOIN DEPARTMENT

--2. FIND ALL PERSONS WITH THEIR DEPARTMENT NAME 
SELECT PERSONNAME, DEPARTMENTNAME 
FROM PERSON P
INNER JOIN DEPARTMENT D
ON P.DEPARTMENTID = D.DEPARTMENTID

--3. FIND ALL PERSONS WITH THEIR DEPARTMENT NAME & CODE. 
SELECT PERSONNAME,DEPARTMENTNAME,DEPARTMENTCODE
FROM PERSON P
JOIN DEPARTMENT D
ON P.DEPARTMENTID = D.DEPARTMENTID

--4. FIND ALL PERSONS WITH THEIR DEPARTMENT CODE AND LOCATION. 
SELECT PERSONNAME,DEPARTMENTCODE,LOCATION 
FROM PERSON P
JOIN DEPARTMENT D
ON P.DEPARTMENTID = D.DEPARTMENTID

--5. FIND THE DETAIL OF THE PERSON WHO BELONGS TO MECHANICAL DEPARTMENT. 
SELECT *
FROM PERSON P
JOIN DEPARTMENT D
ON P.DEPARTMENTID = D.DEPARTMENTID
WHERE D.DEPARTMENTNAME = 'MECHANICAL'

--6. FINAL PERSON’S NAME, DEPARTMENT CODE AND SALARY WHO LIVES IN AHMEDABAD CITY.  
SELECT PERSONNAME,CITY,DEPARTMENTCODE,SALARY
FROM PERSON P
JOIN DEPARTMENT D
ON P.DEPARTMENTID = D.DEPARTMENTID
WHERE P.CITY = 'AHEMADABAD'

--7. FIND THE PERSON'S NAME WHOSE DEPARTMENT IS IN C-BLOCK. 
SELECT PERSONNAME,LOCATION
FROM PERSON P
JOIN DEPARTMENT D
ON P.DEPARTMENTID=D.DEPARTMENTID
WHERE D.LOCATION = 'C-BLOCK'

--8. RETRIEVE PERSON NAME, SALARY & DEPARTMENT NAME WHO BELONGS TO JAMNAGAR CITY. 
SELECT PERSONNAME,CITY,SALARY,DEPARTMENTNAME
FROM PERSON P
JOIN DEPARTMENT D
ON P.DEPARTMENTID = D.DEPARTMENTID
WHERE P.CITY = 'JAMNAGAR'

--9. RETRIEVE PERSON’S DETAIL WHO JOINED THE CIVIL DEPARTMENT AFTER 1-AUG-2001. 
SELECT *
FROM PERSON P
JOIN DEPARTMENT D
ON P.DEPARTMENTID = D.DEPARTMENTID
WHERE JOININGDATE > '2001-08-01'

--10. DISPLAY ALL THE PERSON'S NAME WITH THE DEPARTMENT WHOSE JOINING DATE DIFFERENCE WITH THE CURRENT DATE IS MORE THAN 25 YEARS. 
SELECT * 
FROM PERSON P
JOIN DEPARTMENT D
ON P.DEPARTMENTID = D.DEPARTMENTID
WHERE DATEDIFF(YEAR,P.JOININGDATE,GETDATE()) > 25

--11. FIND DEPARTMENT WISE PERSON COUNTS. 
SELECT COUNT(PERSONID),DEPARTMENTNAME
FROM PERSON P
JOIN DEPARTMENT D
ON P.DEPARTMENTID = D.DEPARTMENTID
GROUP BY DEPARTMENTNAME

--12. GIVE DEPARTMENT WISE MAXIMUM & MINIMUM SALARY WITH DEPARTMENT NAME. 
SELECT DEPARTMENTNAME,MIN(SALARY),MAX(SALARY)
FROM PERSON P
JOIN DEPARTMENT D
ON P.DEPARTMENTID = D.DEPARTMENTID
GROUP BY DEPARTMENTNAME

--13. FIND CITY WISE TOTAL, AVERAGE, MAXIMUM AND MINIMUM SALARY. 
SELECT CITY,SUM(SALARY),AVG(SALARY),MIN(SALARY),MAX(SALARY)
FROM PERSON P
JOIN DEPARTMENT D
ON P.DEPARTMENTID = D.DEPARTMENTID
GROUP BY CITY

--14. FIND THE AVERAGE SALARY OF A PERSON WHO BELONGS TO AHMEDABAD CITY. 
SELECT CITY,AVG(SALARY)
FROM PERSON P
JOIN DEPARTMENT D
ON P.DEPARTMENTID = D.DEPARTMENTID
WHERE CITY = 'AHEMADABAD'
GROUP BY CITY

--15. PRODUCE OUTPUT LIKE: <PERSONNAME> LIVES IN <CITY> AND WORKS IN <DEPARTMENTNAME> DEPARTMENT. (IN SINGLE COLUMN) 
SELECT PERSONNAME +' LIVES IN '+ CITY + ' AND WORKS IN ' + DEPARTMENTNAME +' DEPARTMENT.'
FROM PERSON P
JOIN DEPARTMENT D 
ON P.DEPARTMENTID = D.DEPARTMENTID