--16. PRODUCE OUTPUT LIKE: <PERSONNAME> EARNS <SALARY> FROM <DEPARTMENTNAME> DEPARTMENT MONTHLY. (IN SINGLE COLUMN) 
SELECT PERSONNAME + ' EARNS ' + CAST(SALARY AS VARCHAR) + ' FROM ' + DEPARTMENTNAME + ' DEPARTMENT MONTHLY '
FROM PERSON P 
JOIN DEPARTMENT D
ON P.DEPARTMENTID = D.DEPARTMENTID

--17. FIND CITY & DEPARTMENT WISE TOTAL, AVERAGE & MAXIMUM SALARIES. 
SELECT CITY,SUM(SALARY),AVG(SALARY),MAX(SALARY)
FROM PERSON P
JOIN DEPARTMENT D
ON P.DEPARTMENTID = D.DEPARTMENTID
GROUP BY CITY

SELECT DEPARTMENTNAME,SUM(SALARY),AVG(SALARY),MAX(SALARY)
FROM PERSON P
JOIN DEPARTMENT D
ON P.DEPARTMENTID = D.DEPARTMENTID
GROUP BY DEPARTMENTNAME

--18. FIND ALL PERSONS WHO DO NOT BELONG TO ANY DEPARTMENT. 
SELECT PERSONNAME,DEPARTMENTNAME
FROM PERSON P
LEFT JOIN DEPARTMENT D
ON P.DEPARTMENTID = D.DEPARTMENTID
WHERE DEPARTMENTNAME IS NULL

--19. FIND ALL DEPARTMENTS WHOSE TOTAL SALARY IS EXCEEDING 100000.
SELECT DEPARTMENTNAME,SUM(SALARY)
FROM PERSON P
JOIN DEPARTMENT D
ON P.DEPARTMENTID = D.DEPARTMENTID
GROUP BY DEPARTMENTNAME
HAVING SUM(SALARY) > 100000