--20. LIST ALL DEPARTMENTS WHO HAVE NO PERSON. 
SELECT DEPARTMENTNAME
FROM PERSON P
JOIN DEPARTMENT D
ON P.DEPARTMENTID = D.DEPARTMENTID
GROUP BY DEPARTMENTNAME
HAVING COUNT(PERSONID) = 0

--21. LIST OUT DEPARTMENT NAMES IN WHICH MORE THAN TWO PERSONS ARE WORKING. 
SELECT DEPARTMENTNAME,COUNT(PERSONID)
FROM PERSON P
JOIN DEPARTMENT D
ON P.DEPARTMENTID = D.DEPARTMENTID
GROUP BY DEPARTMENTNAME
HAVING COUNT(PERSONID) > 2

--22. GIVE A 10% INCREMENT IN THE COMPUTER DEPARTMENT EMPLOYEE’S SALARY. (USE UPDATe)
UPDATE PERSON SET SALARY = SALARY*1.1
SELECT PERSONNAME,SALARY,DEPARTMENTNAME
FROM PERSON P
JOIN DEPARTMENT D
ON P.DEPARTMENTID = D.DEPARTMENTID
WHERE DEPARTMENTNAME = 'COMPUTER'
