--21. DISPLAY AVERAGE RESULT OF EACH BRANCH AND SORT THEM IN ASCENDING ORDER BY SPI. 
SELECT AVG(SPI),BRANCH
FROM STUDENT_INFO S
INNER JOIN RESULT R
ON S.RNO = R.RNO
GROUP BY BRANCH
ORDER BY AVG(SPI) ASC

--22. DISPLAY HIGHEST SPI FROM EACH BRANCH AND SORT THEM IN DESCENDING ORDER. 
SELECT MAX(SPI),BRANCH
FROM STUDENT_INFO S
INNER JOIN RESULT R
ON S.RNO = R.RNO
GROUP BY BRANCH
ORDER BY MAX(SPI) DESC

--23. DISPLAY AVERAGE RESULT OF EACH BRANCH AND SORT THEM IN ASCENDING ORDER BY SPI. 
SELECT AVG(SPI),BRANCH
FROM STUDENT_INFO S
INNER JOIN RESULT R
ON S.RNO = R.RNO
GROUP BY BRANCH
ORDER BY AVG(SPI) ASC

--24. DISPLAY HIGHEST SPI FROM EACH BRANCH AND SORT THEM IN DESCENDING ORDER. 
SELECT MAX(SPI),BRANCH
FROM STUDENT_INFO S
INNER JOIN RESULT R
ON S.RNO = R.RNO
GROUP BY BRANCH
ORDER BY MAX(SPI) DESC

--25. DISPLAY BRANCHES WHERE DIFFERENCE BETWEEN MAX AND MIN SPI IS GREATER THAN 1. 
SELECT BRANCH,MAX(SPI)-MIN(SPI)
FROM STUDENT_INFO S
INNER JOIN RESULT R
ON S.RNO = R.RNO
GROUP BY BRANCH
HAVING MAX(SPI) - MIN(SPI) > 1
