SELECT * FROM STUDENT_INFO
SELECT * FROM RESULT

--1. COMBINE INFORMATION FROM STUDENT AND RESULT TABLE USING CROSS JOIN (CARTESIAN PRODUCT). 
SELECT * 
FROM STUDENT_INFO S 
CROSS JOIN RESULT R

--2. PERFORM INNER JOIN ON STUDENT AND RESULT TABLES. 
SELECT *
FROM STUDENT_INFO S
INNER JOIN RESULT R
ON S.RNO = R.RNO

--3. PERFORM THE LEFT OUTER JOIN ON STUDENT AND RESULT TABLES. 
SELECT *
FROM STUDENT_INFO S
LEFT JOIN RESULT R
ON S.RNO = R.RNO

--4. PERFORM THE RIGHT OUTER JOIN ON STUDENT AND RESULT TABLES. 
SELECT * 
FROM STUDENT_INFO S
RIGHT OUTER JOIN RESULT R
ON S.RNO = R.RNO

--5. PERFORM THE FULL OUTER JOIN ON STUDENT AND RESULT TABLES. 
SELECT * 
FROM STUDENT_INFO S
FULL OUTER JOIN RESULT R
ON S.RNO = R.RNO

--6. DISPLAY RNO, NAME, BRANCH AND SPI OF ALL STUDENTS. 
SELECT S.RNO,NAME,BRANCH,SPI
FROM STUDENT_INFO S
INNER JOIN RESULT R
ON S.RNO = R.RNO

--7. DISPLAY RNO, NAME, BRANCH AND SPI OF CE BRANCH STUDENTS ONLY. 
SELECT S.RNO,NAME,BRANCH,SPI
FROM STUDENT_INFO S
INNER JOIN RESULT R
ON R.RNO = S.RNO
WHERE S.BRANCH = 'CE'

--8. DISPLAY RNO, NAME, BRANCH AND SPI OF STUDENTS OTHER THAN EC BRANCH. 
SELECT S.RNO,NAME,BRANCH,SPI
FROM STUDENT_INFO S
INNER JOIN RESULT R
ON S.RNO = R.RNO
WHERE S.BRANCH <> 'EC'

--9. DISPLAY RNO, NAME AND SPI OF STUDENTS WHOSE SPI IS GREATER THAN 8. 
SELECT S.RNO,NAME,SPI
FROM STUDENT_INFO S
INNER JOIN RESULT R
ON S.RNO = R.RNO
WHERE R.SPI > 8

--10. DISPLAY RNO, NAME AND BRANCH OF STUDENTS WHOSE SPI IS LESS THAN 8.
SELECT S.RNO,NAME,BRANCH 
FROM STUDENT_INFO S
INNER JOIN RESULT R
ON R.RNO = S.RNO
WHERE SPI < 8

--11. DISPLAY AVERAGE RESULT OF EACH BRANCH. 
SELECT AVG(SPI),BRANCH
FROM STUDENT_INFO S
INNER JOIN RESULT R
ON S.RNO = R.RNO
GROUP BY BRANCH

--12. DISPLAY AVERAGE RESULT OF CE AND ME BRANCH. 
SELECT AVG(SPI),BRANCH
FROM STUDENT_INFO S
INNER JOIN RESULT R
ON S.RNO = R.RNO
WHERE BRANCH IN ('CE','ME')
GROUP BY BRANCH

--13. DISPLAY MAXIMUM AND MINIMUM SPI OF EACH BRANCH. 
SELECT BRANCH,MIN(SPI) min_spi ,MAX(SPI) max_spi
FROM STUDENT_INFO S
INNER JOIN RESULT R
ON S.RNO = R.RNO
GROUP BY BRANCH

--14. DISPLAY BRANCH-WISE STUDENT COUNT IN DESCENDING ORDER. 
SELECT BRANCH,COUNT(S.RNO) std_no
FROM STUDENT_INFO S
INNER JOIN RESULT R
ON S.RNO = R.RNO
GROUP BY BRANCH
ORDER BY COUNT(SPI) DESC

--15. DISPLAY BRANCH-WISE TOTAL SPI OF STUDENTS.
SELECT BRANCH,SUM(SPI)
FROM STUDENT_INFO S
INNER JOIN RESULT R
ON S.RNO = R.RNO 
GROUP BY BRANCH