--16. DISPLAY BRANCH-WISE NUMBER OF STUDENTS HAVING SPI GREATER THAN 8.
SELECT BRANCH,COUNT(S.RNO) 
FROM STUDENT_INFO S
INNER JOIN RESULT R
ON S.RNO = R.RNO
WHERE SPI > 8
GROUP BY BRANCH

--17. DISPLAY BRANCH-WISE NUMBER OF STUDENTS HAVING SPI LESS THAN 8. 
SELECT BRANCH,COUNT(S.RNO)
FROM STUDENT_INFO S
INNER JOIN RESULT R
ON S.RNO = R.RNO
WHERE SPI < 8
GROUP BY BRANCH

--18. DISPLAY BRANCH-WISE AVERAGE SPI GREATER THAN 7. 
SELECT BRANCH,AVG(SPI)
FROM STUDENT_INFO S
INNER JOIN RESULT R
ON S.RNO = R.RNO
GROUP BY BRANCH
HAVING AVG(SPI)>7

--19. DISPLAY BRANCHES HAVING MORE THAN 1 STUDENTS. 
SELECT BRANCH,COUNT(S.RNO)
FROM STUDENT_INFO S
INNER JOIN RESULT R
ON S.RNO = R.RNO
GROUP BY BRANCH
HAVING COUNT(S.RNO)>1


--20. DISPLAY BRANCHES WHERE MAXIMUM SPI IS GREATER THAN 9.
SELECT BRANCH,MAX(SPI)
FROM STUDENT_INFO S
INNER JOIN RESULT R
ON S.RNO = R.RNO
GROUP BY BRANCH
HAVING MAX(SPI)>9
