SELECT * FROM LIBRARYBORROWING
--I. DISPLAY THE TOTAL FINE AMOUNT COLLECTED FOR EACH BOOK GENRE. 
SELECT BOOKGENRE,SUM(FINEAMOUNT) FROM LIBRARYBORROWING GROUP BY BOOKGENRE
SELECT * FROM LIBRARYBORROWING

--II. FIND THE AVERAGE NUMBER OF DAYS BORROWED FOR EACH BOOK GENRE. 
--III. DISPLAY THE NUMBER OF BORROWING RECORDS FOR EACH MEMBER. 
--IV. FIND THE MAXIMUM FINE AMOUNT PAID IN EACH BOOK GENRE. 
--V. DISPLAY THE MINIMUM DAYS BORROWED FOR EACH BOOK GENRE. 
--VI. FIND THE TOTAL NUMBER OF DAYS BOOKS WERE BORROWED BY EACH MEMBER. 
--VII. DISPLAY THE AVERAGE FINE AMOUNT PAID BY EŪACH MEMBER. 
--VIII. FIND THE HIGHEST NUMBER OF DAYS BORROWED BY EACH MEMBER. 
--IX. FIND THE DIFFERENCE BETWEEN THE HIGHEST AND LOWEST FINE FOR EACH GENRE. 
--X. FIND HOW MANY TIMES HAS EACH MEMBER BORROWED A BOOK. 